# Generated by Django 4.2.13 on 2024-05-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_snack_alter_walk_options_alter_walk_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='snacks',
            field=models.ManyToManyField(to='main_app.snack'),
        ),
    ]
